/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.java.sample;

import java.util.concurrent.atomic.AtomicInteger;

import com.google.common.util.concurrent.AtomicDouble;

public class App {
    public static void main(String[] args) {
        String test = "test";

        new AtomicDouble();

        int a = 1;

        int[] b = new int[] { 4, 5, 6 };

        if (a == 1) {
            System.out.println(test + a);
        } else {
            System.out.println("Not 1" + b);
        }
    }
}
